<?php

/*
 *
 * Developed by Clayton Dukes <cdukes@logzilla.pro>
 * Copyright (c) 2009 http://www.gdd.net
 * All rights reserved.
 *
 * Changelog:
 * 2009-06-17 - created
 *
 */

$basePath = dirname( __FILE__ );
require_once($basePath . "/common_funcs.php");
$dbLink = db_connect_syslog(DBADMIN, DBADMINPW);
session_start();

$rpt_type = get_input('rpt_type');

/** Error reporting */
error_reporting(E_ALL);
ini_set('memory_limit', '512M');
ini_set('max_execution_time', '120');

/** Include path **/
ini_set('include_path', ini_get('include_path').":$basePath/../PHPExcel/");


/** PHPExcel */
include 'PHPExcel.php';

/** PHPExcel_Writer_Excel2007 */
include 'PHPExcel/Writer/Excel2007.php';
include 'PHPExcel/IOFactory.php';

$date = date("Y-m-d");
$time = date("H:i:s");

function get_server() {
    $protocol = 'http';
    if (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == '443') {
        $protocol = 'https';
    }
    $host = $_SERVER['HTTP_HOST'];
    $baseUrl = $protocol . '://' . $host;
    if (substr($baseUrl, -1)=='/') {
        $baseUrl = substr($baseUrl, 0, strlen($baseUrl)-1);
    }
    return $baseUrl;
}
// Create new PHPExcel object
$objPHPExcel = new PHPExcel();

// Set properties
$objPHPExcel->getProperties()->setCreator("LogZilla, LLC.");
$objPHPExcel->getProperties()->setLastModifiedBy($_SESSION['username']);
$objPHPExcel->getProperties()->setTitle("LogZilla Syslog Report");
$objPHPExcel->getProperties()->setSubject("Syslog Report for $date $time");
$objPHPExcel->getProperties()->setDescription("Generated by ".get_server(). $_SESSION['PROGNAME']);

$query = "SELECT * FROM ".$_SESSION['viewname'];
$results = perform_query($query, $dbLink);
$n = 0;
// die($query);
while($row = fetch_array($results)) {
    $result_array[$n] = $row;
    $n++;
}


$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'EID');
// $objPHPExcel->getActiveSheet()->SetCellValue('B1', 'Sequence');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'Host');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'Facility');
$objPHPExcel->getActiveSheet()->SetCellValue('D1', 'Severity');
$objPHPExcel->getActiveSheet()->SetCellValue('E1', 'Program');
$objPHPExcel->getActiveSheet()->SetCellValue('F1', 'Mnemonic');
$objPHPExcel->getActiveSheet()->SetCellValue('G1', 'Message');
$objPHPExcel->getActiveSheet()->SetCellValue('H1', 'Received');
$objPHPExcel->getActiveSheet()->SetCellValue('I1', 'Notes');

$objPHPExcel->getActiveSheet()->getStyle('A1:I1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('A1:I1')->getFont()->setSize(14); 

$objPHPExcel->getActiveSheet()->duplicateStyleArray(
        array(
            'font'    => array(
                'bold'      => true
                ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
                ),
            'borders' => array(
                'top'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                    ),
                'bottom'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                    ),
                ),
            'fill' => array(
                'type' => PHPExcel_Style_Fill::FILL_SOLID,
                'startcolor' => array(
                    'rgb' => $_SESSION['EXCEL_HDR'],
                    ),
                ),
            ),
            'A1:I1'
            );

            for($i=0; $i < count($result_array); $i++) {
                $row = $result_array[$i];
                $r = ($i + 2);
                 // echo $row['facility']."<br>";
                 // echo "A{$r}<br>";

                $objPHPExcel->getActiveSheet()->SetCellValue("A{$r}", $row['eid']);
                // Set A{$r} to a Number format
                $objPHPExcel->getActiveSheet()->getStyle("A{$r}")->getNumberFormat()->setFormatCode('0');
                $objPHPExcel->getActiveSheet()->SetCellValue("B{$r}", $row['host']);
                $objPHPExcel->getActiveSheet()->SetCellValue("C{$r}", $row['facility']);
                $objPHPExcel->getActiveSheet()->SetCellValue("D{$r}", $row['severity']);
                $objPHPExcel->getActiveSheet()->SetCellValue("E{$r}", $row['program']);
                $objPHPExcel->getActiveSheet()->SetCellValue("F{$r}", $row['mne']);
                $objPHPExcel->getActiveSheet()->getStyle("G{$r}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
                if ($rpt_type !== "pdf") {
                    $objPHPExcel->getActiveSheet()->SetCellValue("G{$r}", $row['msg']);
                } else {
                    // Wrap long messages so that it fits in a pdf page.
                    $msg = wordwrap($row['msg'], 40, "\n");
                    $objPHPExcel->getActiveSheet()->SetCellValue("G{$r}", $msg);
                }
                $objPHPExcel->getActiveSheet()->SetCellValue("H{$r}", $row['lo']);
                $objPHPExcel->getActiveSheet()->SetCellValue("I{$r}", $row['notes']);
                if ( $r&1 ) {
                    $objPHPExcel->getActiveSheet()->duplicateStyleArray(
                            array(
                                'fill' => array(
                                    'type' => PHPExcel_Style_Fill::FILL_SOLID,
                                    'startcolor' => array(
                                        'rgb' => $_SESSION['EXCEL_DRK'],
                                        ),
                                    ),
                                ),
                            "A${r}:I${r}"
                            );
                } else {
                    $objPHPExcel->getActiveSheet()->duplicateStyleArray(
                            array(
                                'fill' => array(
                                    'type' => PHPExcel_Style_Fill::FILL_SOLID,
                                    'startcolor' => array(
                                        'rgb' => $_SESSION['EXCEL_LT'],
                                        ),
                                    ),
                                ),
                            "A${r}:I${r}"
                            );
                }
            }

$objPHPExcel->getActiveSheet()->setShowGridlines(false);

/* Ugly, commented out for now
$objPHPExcel->getActiveSheet()->getRowDimension('1')->setRowHeight(56);
$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath($basePath . '/../../images/Logo_205x56_transparent_24bit_color.png');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
$objDrawing->setCoordinates('A1');
*/


// Rename sheet
$datetime = date("Y-m-d Hi a");
$objPHPExcel->getActiveSheet()->setTitle("$datetime");
// Autosize Columns
// This doesn't seem to work and I don't know why - I searched the documentation and forums for PHPExcel but still couldn't get it to work
foreach(range('A', 'I') as $columnID) {
    $objPHPExcel->getActiveSheet()->getColumnDimension("$columnID")->setAutoSize(true);
}

switch ($rpt_type) {
    case 'xml':
        $fn = $_SESSION['PROGNAME'] ."_Report_".date("Y-m-d_Hia").".xlsx";
        // redirect output to client browser
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header("Content-Disposition: attachment;filename=".$fn."");
        header('Cache-Control: max-age=0');

        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        $objWriter->save('php://output'); 
            break;
    case 'csv':
        $fn = $_SESSION['PROGNAME'] ."_Report_".date("Y-m-d_Hia").".csv";
        // redirect output to client browser
        header('Content-Type: text/plain');
        header("Content-Disposition: attachment;filename=".$fn."");
        header('Cache-Control: max-age=0');

        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'CSV');
        $objWriter->save('php://output'); 
            break;
    case 'pdf':
        $fn = $_SESSION['PROGNAME'] ."_Report_".date("Y-m-d_Hia").".pdf";
        // redirect output to client browser
        $objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
        $objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
        $objPHPExcel->getActiveSheet()->getPageSetup()->setFitToWidth(1);
        header('Content-Type: application/pdf');
        header("Content-Disposition: attachment;filename=".$fn."");
        header('Cache-Control: max-age=0');

        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'PDF');
        $objWriter->save('php://output'); 
            break;
    default: // Default is Excel5 Format
        $fn = $_SESSION['PROGNAME'] ."_Report_".date("Y-m-d_Hia").".xls";
        // redirect output to client browser
        header('Content-Type: application/vnd.ms-excel');
        header("Content-Disposition: attachment;filename=".$fn."");
        header('Cache-Control: max-age=0');

        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output'); 
}
?>
